### PR TITLE
Shebang versatile compatibility. Required dependencies.

### PR DESCRIPTION
**Pull request by mluis**
OSX compatible shebang.
Pip freeze dependancy list.

### CODE REVIEW

**Comment by ClaymorePT** [comment]
wth is Shebang ? lol

**Comment by ClaymorePT** [comment]
Now a bit more serious

Explain the dependency list. 
The program is only directly requiring lxml and I'mm seeing a lot of other dependencies not being used.

**Comment by mluis** [comment]
That's because your system already has the other ones.
Try running the project under virtualenv.
Requirements.txt is extracted from a pip freeze

**Comment by mluis** [comment]
btw, about shebangs https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by ClaymorePT** [comment]
Its not what I meant.
I'm asking why are you specifying every single module, when you could just have specified *lxml* and *requests*. Also, why are you locking the modules into a specific version?
Did you just copy the *pip freeze* output?

PS: SheBangs -> I know them as HashBangs, hence my initial confusion :)

**Comment by ClaymorePT** [comment]
Updated by -> https://github.com/ClaymorePT/TorrentSearcher/commit/8ca013b063cdb041d445498679ac3c65e24e1c66

**Pull request closed without merging**
